name: odoc-sandbox
channels:
  - conda-forge
  - defaults
dependencies:
  - 'python>=3.8'
  - sphinx
  - pandoc
  - mdformat
  - myst-parser
  # undocumented dependency of myst_parser/parsers/docutils_py > ... > markdown_it/rules_core/linkify.py:
  # https://github.com/executablebooks/markdown-it-py/issues/191
  # (only when --myst-gfm-only=True option used)
  - linkify-it-py
